site_name: Azimuth Operator Documentation
repo_url: https://github.com/azimuth-cloud/azimuth-config
copyright: Copyright &copy; StackHPC 2022
edit_uri: ''

nav:
  - Home: index.md
  - try.md
  - best-practice.md
  - environments.md
  - Repository:
      - repository/index.md
      - repository/secrets.md
      - repository/opentofu.md
  - Configuration:
      - configuration/index.md
      - configuration/01-prerequisites.md
      - configuration/02-deployment-method.md
      - configuration/03-kubernetes-config.md
      - configuration/04-target-cloud.md
      - configuration/05-secret-key.md
      - configuration/06-ingress.md
      - configuration/07-platform-identity.md
      - configuration/08-zenith.md
      - configuration/09-community-images.md
      - configuration/10-kubernetes-clusters.md
      - configuration/11-kubernetes-apps.md
      - configuration/12-caas.md
      - configuration/13-access-control.md
      - configuration/14-monitoring.md
      - configuration/15-disaster-recovery.md
      - configuration/16-local-customisations.md
  - Deployment:
      - deployment/index.md
      - deployment/automation.md
      - deployment/testing.md
  - Debugging:
      - debugging/index.md
      - debugging/access-k3s.md
      - debugging/access-ha.md
      - debugging/access-monitoring.md
      - debugging/zenith-services.md
      - debugging/consul.md
      - debugging/kubernetes.md
      - debugging/caas.md
  - Developing:
      - developing/index.md

theme:
  name: material
  logo: assets/azimuth-logo-white.png
  favicon: assets/azimuth-logo-blue.png
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top

extra_css:
  - assets/extra.css

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      toc_depth: 3

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
