#####
# This file contains environment-specific secrets for an Azimuth deployment
#
# It should be encrypted if stored in version control
# https://stackhpc.github.io/azimuth-config/repository/secrets/
#####

# https://stackhpc.github.io/azimuth-config/configuration/05-secret-key/
# The secret key for signing Azimuth cookies
azimuth_secret_key: "<secure secret key>"

# https://stackhpc.github.io/azimuth-config/configuration/07-platform-identity/#keycloak-admin-password
# The admin password for the Keycloak master realm
keycloak_admin_password: "<secure password>"

# https://stackhpc.github.io/azimuth-config/configuration/08-zenith/
# The secret key for signing Zenith registrar tokens
zenith_registrar_subdomain_token_signing_key: "<secure secret key>"

# https://stackhpc.github.io/azimuth-config/configuration/10-kubernetes-clusters/#harbor-registry
# The password for the Harbor admin account
harbor_admin_password: "<secure password>"
# The secret key for Harbor
harbor_secret_key: "<secure secret key>"

# https://stackhpc.github.io/azimuth-config/configuration/14-monitoring/#accessing-web-interfaces
# The admin password for Azimuth administrative dashboards
admin_dashboard_ingress_basic_auth_password: "<secure password>"

# https://stackhpc.github.io/azimuth-config/configuration/14-monitoring/#slack-alerts
# The Slack webhook URL for monitoring alerts
alertmanager_config_slack_webhook_url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX

# https://stackhpc.github.io/azimuth-config/configuration/15-disaster-recovery/
# The S3 access key and secret for backups
velero_aws_access_key_id: "<access key id>"
velero_aws_secret_access_key: "<secret key>"
